"""Graduation gates — evaluates whether a strategy meets the 6 graduation criteria."""

import os
from dataclasses import dataclass, field
from typing import Any

from astra.alpaca.monitor import PerformanceSnapshot
from astra.pipeline.runner import PipelineResult
from astra.optimizer.history import OptimizationHistory


_DISCLAIMER = (
    "ASTRA research results are not profitability guarantees. "
    "Past performance does not predict future results. "
    "This gate evaluation was generated by ASTRA for research purposes only."
)


@dataclass
class GateResult:
    gate_name: str = ""
    status: str = "FAILED"
    actual_value: float = 0.0
    threshold_value: float = 0.0
    gap: float = 0.0
    evidence: str = ""


@dataclass
class GateCheckResult:
    overall_status: str = "NOT_READY"
    gates: dict[str, GateResult] = field(default_factory=dict)
    gates_passed: int = 0
    gates_total: int = 6
    closest_to_passing: str | None = None
    plain_english_summary: str = ""
    disclaimer: str = _DISCLAIMER


_GATE_NAMES = [
    "dsr",
    "annual_return",
    "max_drawdown",
    "min_trades",
    "max_degradation",
    "min_calendar_days",
]


class GraduationError(Exception):
    ...


class GraduationGates:
    def __init__(self, config: dict[str, Any] | None = None):
        cfg = config or {}
        self._thresholds = {
            "dsr": float(cfg.get("MIN_DSR", os.environ.get("MIN_DSR", 1.5))),
            "annual_return": float(cfg.get("MIN_ANNUAL_RETURN", os.environ.get("MIN_ANNUAL_RETURN", 0.05))),
            "max_drawdown": float(cfg.get("MAX_DRAWDOWN", os.environ.get("MAX_DRAWDOWN", 0.20))),
            "min_trades": float(cfg.get("MIN_TRADES", os.environ.get("MIN_TRADES", 20))),
            "max_degradation": float(cfg.get("MAX_DEGRADATION", os.environ.get("MAX_DEGRADATION", 0.2))),
            "min_calendar_days": float(cfg.get("MIN_CALENDAR_DAYS", os.environ.get("MIN_CALENDAR_DAYS", 5))),
        }
        for name, val in self._thresholds.items():
            if val < 0:
                raise ValueError(f"Threshold for {name} must be positive, got {val}")

    def check(
        self,
        snapshot: PerformanceSnapshot,
        pipeline_result: PipelineResult,
        optimization_history: OptimizationHistory | None = None,
    ) -> GateCheckResult:
        gates: dict[str, GateResult] = {}
        gates_passed = 0

        backtest_metrics = pipeline_result.backtest_metrics or {}
        cpcv_summary = pipeline_result.cpcv_summary or {}
        dsr_value = float(cpcv_summary.get("dsr", backtest_metrics.get("dsr", 0.0)))
        degradation = snapshot.degradation_report

        gate_defs = [
            self._check_dsr(dsr_value),
            self._check_annual_return(snapshot.annualized_return),
            self._check_max_drawdown(snapshot.max_drawdown),
            self._check_min_trades(snapshot.total_trades),
            self._check_max_degradation(degradation.overall_degradation_score if degradation else 1.0),
            self._check_min_calendar_days(snapshot.days_deployed),
        ]

        for g in gate_defs:
            gates[g.gate_name] = g
            if g.status == "PASSED":
                gates_passed += 1

        overall_status = "GRADUATED" if gates_passed == 6 else "NOT_READY"

        closest_to_passing = None
        smallest_gap = float("inf")
        for g in gates.values():
            if g.status == "FAILED" and 0 < g.gap < smallest_gap:
                smallest_gap = g.gap
                closest_to_passing = g.gate_name

        summary_lines = [
            f"Gate evaluation: {gates_passed}/6 gates passed. Status: {overall_status}."
        ]
        for g in gates.values():
            summary_lines.append(f"  {g.gate_name}: {g.status} ({g.evidence})")
        if closest_to_passing:
            summary_lines.append(f"  Closest to passing: {closest_to_passing}")
        plain_english_summary = "\n".join(summary_lines)

        return GateCheckResult(
            overall_status=overall_status,
            gates=gates,
            gates_passed=gates_passed,
            gates_total=6,
            closest_to_passing=closest_to_passing,
            plain_english_summary=plain_english_summary,
        )

    def _check_dsr(self, dsr: float) -> GateResult:
        threshold = self._thresholds["dsr"]
        gap = threshold - dsr
        passed = dsr >= threshold
        return GateResult(
            gate_name="dsr",
            status="PASSED" if passed else "FAILED",
            actual_value=dsr,
            threshold_value=threshold,
            gap=round(gap, 4),
            evidence=f"Deflated Sharpe Ratio is {dsr:.2f}, threshold is {threshold:.1f}",
        )

    def _check_annual_return(self, ann_ret: float) -> GateResult:
        threshold = self._thresholds["annual_return"]
        gap = threshold - ann_ret
        passed = ann_ret >= threshold
        return GateResult(
            gate_name="annual_return",
            status="PASSED" if passed else "FAILED",
            actual_value=ann_ret,
            threshold_value=threshold,
            gap=round(gap, 4),
            evidence=f"Annualized return is {ann_ret:.2%}, threshold is {threshold:.0%}",
        )

    def _check_max_drawdown(self, dd: float) -> GateResult:
        threshold = self._thresholds["max_drawdown"]
        gap = dd - threshold
        passed = dd <= threshold
        return GateResult(
            gate_name="max_drawdown",
            status="PASSED" if passed else "FAILED",
            actual_value=dd,
            threshold_value=threshold,
            gap=round(gap, 4),
            evidence=f"Max drawdown is {dd:.2%}, threshold is {threshold:.0%}",
        )

    def _check_min_trades(self, trades: int) -> GateResult:
        threshold = self._thresholds["min_trades"]
        gap = threshold - trades
        passed = trades >= threshold
        return GateResult(
            gate_name="min_trades",
            status="PASSED" if passed else "FAILED",
            actual_value=float(trades),
            threshold_value=threshold,
            gap=round(gap, 4),
            evidence=f"Total trades is {trades}, threshold is {int(threshold)}",
        )

    def _check_max_degradation(self, deg_score: float) -> GateResult:
        threshold = self._thresholds["max_degradation"]
        gap = deg_score - threshold
        passed = deg_score <= threshold
        return GateResult(
            gate_name="max_degradation",
            status="PASSED" if passed else "FAILED",
            actual_value=deg_score,
            threshold_value=threshold,
            gap=round(gap, 4),
            evidence=f"Degradation score is {deg_score:.2f}, threshold is {threshold:.1f}",
        )

    def _check_min_calendar_days(self, days: int) -> GateResult:
        threshold = self._thresholds["min_calendar_days"]
        gap = threshold - days
        passed = days >= threshold
        return GateResult(
            gate_name="min_calendar_days",
            status="PASSED" if passed else "FAILED",
            actual_value=float(days),
            threshold_value=threshold,
            gap=round(gap, 4),
            evidence=f"Days deployed is {days}, threshold is {int(threshold)}",
        )
