"""Strategy packager — produces a self-contained portable Python strategy file."""

import hashlib
import os
import re
import subprocess
import sys
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone

from astra.builder.generator import BuildResult
from astra.planner.spec import StrategySpec
from astra.graduation import GraduationCertificate
from astra.pipeline.runner import PipelineResult
from astra.alpaca.monitor import PerformanceSnapshot
from astra.export.validator import ExportValidator, ExportValidationError


_INLINED_BASE_STRATEGY = '''
from abc import ABC, abstractmethod

import pandas as pd


class BaseStrategy(ABC):
    STRATEGY_TYPE: str = ""
    STRATEGY_HYPOTHESIS: str = ""

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        ...

    @abstractmethod
    def get_parameters(self) -> dict:
        ...

    @abstractmethod
    def get_parameter_bounds(self) -> dict:
        ...
'''


_DISCLAIMER = (
    "ASTRA research results are not profitability guarantees. "
    "Past performance does not predict future results. "
    "This file was generated by ASTRA for research purposes only."
)


@dataclass
class ExportPackage:
    export_id: str = ""
    session_id: str = ""
    spec_id: str = ""
    certificate_id: str = ""
    exported_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    strategy_file: str = ""
    report_file: str = ""
    export_dir: str = ""
    checksum: str = ""
    disclaimer: str = _DISCLAIMER

    def to_json(self) -> str:
        import json
        from dataclasses import asdict

        data = asdict(self)
        data["exported_at"] = self.exported_at.isoformat()
        return json.dumps(data, indent=2, default=str)


_EXPORTED_DOCSTRING_TEMPLATE = '''{strategy_name}
{underline}

What This Strategy Does
----------------------
{user_idea}

Market Conditions Validated
--------------------------
Backtest Period: {backtest_start} to {backtest_end}
Asset Class: {asset_class}
Symbols: {symbols}
Timeframe: {timeframe}
Data Source: {data_source}
Market Hypothesis: {hypothesis}

Entry and Exit Conditions
------------------------
Entry: {entry}
Exit: {exit}

Risk Parameters
--------------
Max Position Size: {position_size:.0%}
Stop Loss: {stop_loss}
Take Profit: {take_profit}
Max Positions: {max_positions}

Limitations
----------
{limitations}

Disclaimer
---------
{disclaimer}
'''


class StrategyPackager:
    def __init__(self, export_dir: str):
        self._export_dir = export_dir
        self._validator = ExportValidator()

    def package(
        self,
        build_result: BuildResult,
        spec: StrategySpec,
        certificate: GraduationCertificate,
        pipeline_result: PipelineResult,
        snapshot: PerformanceSnapshot,
    ) -> ExportPackage:
        os.makedirs(self._export_dir, exist_ok=True)

        export_id = str(uuid.uuid4())
        date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
        short_id = spec.spec_id[:8] if len(spec.spec_id) >= 8 else spec.spec_id
        filename = f"astra_export_{spec.strategy_type}_{short_id}_{date_str}.py"
        export_path = os.path.join(self._export_dir, filename)

        with open(build_result.strategy_file) as f:
            original_code = self._sanitize_strategy_code(f.read())

        risk_lines = []
        if spec.stop_loss is not None:
            risk_lines.append(f"STOP_LOSS = {spec.stop_loss}")
        if spec.take_profit is not None:
            risk_lines.append(f"TAKE_PROFIT = {spec.take_profit}")
        risk_lines.append(f"MAX_POSITION_SIZE = {spec.position_size}")
        if spec.max_positions:
            risk_lines.append(f"MAX_POSITIONS = {spec.max_positions}")

        param_lines = []
        for key, val in build_result.initial_parameters.items():
            param_lines.append(f"{key.upper()} = {val!r}")

        symbols_str = ", ".join(f"{s!r}" for s in spec.symbols)
        limitations_str = "\n".join(f"  {i+1}. {lim}" for i, lim in enumerate(certificate.limitations))

        entry_str = spec.entry_conditions[0] if spec.entry_conditions else ""
        exit_str = spec.exit_conditions[0] if spec.exit_conditions else ""
        stop_loss_str = str(spec.stop_loss) if spec.stop_loss is not None else "Not set"
        take_profit_str = str(spec.take_profit) if spec.take_profit is not None else "Not set"
        max_positions_str = str(spec.max_positions) if spec.max_positions else "Not set"

        strategy_name = f"ASTRA Export: {spec.strategy_type.replace('_', ' ').title()} ({', '.join(spec.symbols)})"

        docstring = _EXPORTED_DOCSTRING_TEMPLATE.format(
            strategy_name=strategy_name,
            underline="=" * len(strategy_name),
            user_idea=spec.user_idea,
            backtest_start=spec.backtest_start,
            backtest_end=spec.backtest_end,
            asset_class=spec.asset_class,
            symbols=", ".join(spec.symbols),
            timeframe=spec.timeframe,
            data_source=spec.data_source,
            hypothesis=spec.market_hypothesis,
            entry=entry_str,
            exit=exit_str,
            position_size=spec.position_size,
            stop_loss=stop_loss_str,
            take_profit=take_profit_str,
            max_positions=max_positions_str,
            limitations=limitations_str,
            disclaimer=_DISCLAIMER,
        )

        certificate_lines = [
            "# ============================================================",
            "# GRADUATION CERTIFICATE",
            f"# Certificate ID: {certificate.certificate_id}",
            f"# Session ID: {certificate.session_id}",
            f"# Spec ID: {certificate.spec_id}",
            f"# Issued: {certificate.issued_at.isoformat()}",
            f"# Strategy Type: {certificate.strategy_type}",
            f"# Optimization Cycles: {certificate.optimization_cycles}",
        ]
        for gr in certificate.gate_results.values():
            certificate_lines.append(
                f"#   Gate [{gr.status}] {gr.gate_name}: actual={gr.actual_value}, "
                f"threshold={gr.threshold_value}, gap={gr.gap}"
            )
        certificate_lines.append("# ============================================================")
        header = "\n".join(certificate_lines)

        backtest_metrics = pipeline_result.backtest_metrics or {}

        gates_pass_count = sum(1 for g in certificate.gate_results.values() if g.status == "PASSED")

        metadata_dict_lines = [
            "STRATEGY_METADATA = {",
            f'    "certificate_id": {certificate.certificate_id!r},',
            f'    "session_id": {certificate.session_id!r},',
            f'    "spec_id": {spec.spec_id!r},',
            f'    "strategy_type": {spec.strategy_type!r},',
            f'    "symbols": [{symbols_str}],',
            f'    "issued_at": {certificate.issued_at.isoformat()!r},',
            f'    "gates_passed": {gates_pass_count},'
            f'    "optimization_cycles": {certificate.optimization_cycles},',
            f'    "backtest_sharpe": {backtest_metrics.get("mean_sharpe", "N/A")!r},',
            f'    "backtest_dsr": {backtest_metrics.get("dsr", "N/A")!r},',
            f'    "paper_return": {snapshot.total_return!r},',
            f'    "paper_sharpe": {snapshot.sharpe_ratio!r},',
            f'    "paper_max_drawdown": {snapshot.max_drawdown!r},',
            f'    "paper_win_rate": {snapshot.win_rate!r},',
            f'    "paper_days_deployed": {snapshot.days_deployed!r},',
            f'    "paper_total_trades": {snapshot.total_trades!r},',
            f'    "pipeline_id": {pipeline_result.pipeline_id!r},',
            "}",
        ]
        metadata_block = "\n".join(metadata_dict_lines)

        param_names = list(build_result.initial_parameters.keys())
        param_dict_items = ", ".join(f"\"{k.upper()}\": {k.upper()}" for k in param_names)

        demo_harness = f'''
# ============================================================
# Demo Harness — run this file directly to see the strategy in action
# ============================================================
if __name__ == "__main__":
    import pandas as pd
    import numpy as np
    from datetime import datetime, timedelta

    print("ASTRA Generated Strategy — Demo Mode")
    print("=" * 50)

    dates = pd.bdate_range(end=datetime.today(), periods=504)
    close = np.random.randn(504).cumsum() + 100
    data = pd.DataFrame({{"close": close}}, index=dates)

    strategy_cls = {build_result.strategy_class_name}
    kwargs = {{{param_dict_items}}}
    strategy = strategy_cls(**kwargs)

    signals = strategy.generate_signals(data)
    print(f"Generated {{len(signals)}} signal periods")
    print(f"Long signals: {{(signals == 1).sum()}}")
    print(f"Flat periods: {{(signals == 0).sum()}}")
    print(f"Strategy type: {{strategy_cls.STRATEGY_TYPE}}")
    print(f"Hypothesis: {{strategy_cls.STRATEGY_HYPOTHESIS}}")
    print()
    print("WARNING: This uses random data for demonstration only.")
    print("Run with real market data for meaningful analysis.")
'''

        exported_lines = [
            '"""',
            docstring,
            '"""',
            "",
            header,
            "",
            "# Risk Limits",
            *risk_lines,
            "",
            "# Parameters",
            *param_lines,
            "",
            metadata_block,
            "",
            original_code,
            "",
            demo_harness,
        ]

        exported_content = "\n".join(exported_lines)

        formatted = self._try_format(exported_content)
        exported_content = formatted if formatted is not None else exported_content

        with open(export_path, "w") as f:
            f.write(exported_content)

        validation = self._validator.validate(export_path)
        if not validation.passed:
            raise ExportValidationError(
                f"Export validation failed: {'; '.join(validation.failures)}"
            )

        import_error = self._try_import_test(export_path)
        if import_error:
            validation.warnings.append(f"Import test warning: {import_error}")

        checksum = hashlib.sha256(exported_content.encode("utf-8")).hexdigest()

        return ExportPackage(
            export_id=export_id,
            session_id=spec.spec_id,
            spec_id=spec.spec_id,
            certificate_id=certificate.certificate_id,
            strategy_file=export_path,
            export_dir=self._export_dir,
            checksum=checksum,
        )

    @staticmethod
    def _sanitize_strategy_code(code: str) -> str:
        has_astra_import = "from astra.builder.templates" in code or "import astra" in code
        if not has_astra_import:
            return code

        code = re.sub(
            r"^from\s+astra\.builder\.templates\s+import\s+.*$",
            "from inlined_base import BaseStrategy",
            code,
            flags=re.MULTILINE,
        )
        code = re.sub(
            r"^import\s+astra.*$",
            "",
            code,
            flags=re.MULTILINE,
        )

        inlined = _INLINED_BASE_STRATEGY.replace(
            "from abc import ABC, abstractmethod\n\nimport pandas as pd\n\n\nclass BaseStrategy(ABC):",
            "class BaseStrategy:",
        )
        inlined = inlined.replace("@abstractmethod\n    ", "")
        code = inlined + "\n" + code
        return code

    def _try_format(self, code: str) -> str | None:
        for tool in ("ruff", "black"):
            try:
                result = subprocess.run(
                    [tool, "-", "--quiet"],
                    input=code,
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                if result.returncode == 0 and result.stdout:
                    return result.stdout
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue
        return None

    def _try_import_test(self, file_path: str) -> str | None:
        try:
            import importlib.util

            spec_name = f"_astra_export_test_{uuid.uuid4().hex[:8]}"
            spec = importlib.util.spec_from_file_location(spec_name, file_path)
            if spec is None or spec.loader is None:
                return "Could not load module spec"
            mod = importlib.util.module_from_spec(spec)
            sys.modules[spec_name] = mod
            spec.loader.exec_module(mod)
            del sys.modules[spec_name]
            return None
        except Exception as e:
            return f"Module import failed: {e}"

    def _update_report_file(self, package: ExportPackage, report_path: str) -> ExportPackage:
        package.report_file = report_path
        return package
