"""PDF report generator — produces a summary report for graduated strategies."""

import os
from datetime import datetime, timezone
from typing import Any

from astra.planner.spec import StrategySpec
from astra.graduation import GraduationCertificate
from astra.pipeline.runner import PipelineResult
from astra.alpaca.monitor import PerformanceSnapshot
from astra.export.packager import ExportPackage


_DISCLAIMER = (
    "ASTRA research results are not profitability guarantees. "
    "Past performance does not predict future results. "
    "This report was generated by ASTRA for research purposes only."
)


class ReportGenerator:
    def __init__(self, export_dir: str):
        self._export_dir = export_dir

    def generate(
        self,
        spec: StrategySpec,
        certificate: GraduationCertificate,
        pipeline_result: PipelineResult,
        snapshot: PerformanceSnapshot,
        export_package: ExportPackage,
    ) -> str:
        os.makedirs(self._export_dir, exist_ok=True)

        date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
        short_id = spec.spec_id[:8] if len(spec.spec_id) >= 8 else spec.spec_id
        filename = f"astra_report_{spec.strategy_type}_{short_id}_{date_str}.pdf"
        report_path = os.path.join(self._export_dir, filename)

        content = self._build_content(
            spec, certificate, pipeline_result, snapshot, export_package
        )

        self._write_pdf(report_path, content, spec, certificate, export_package)

        return report_path

    def _build_content(
        self,
        spec: StrategySpec,
        certificate: GraduationCertificate,
        pipeline_result: PipelineResult,
        snapshot: PerformanceSnapshot,
        export_package: ExportPackage,
    ) -> list[dict[str, Any]]:
        backtest = pipeline_result.backtest_metrics or {}
        cpcv = pipeline_result.cpcv_summary or {}

        pages: list[dict[str, Any]] = []

        pages.append({
            "type": "cover",
            "title": f"ASTRA Strategy Report: {spec.strategy_type.replace('_', ' ').title()}",
            "subtitle": f"Symbols: {', '.join(spec.symbols)}",
            "certificate_id": certificate.certificate_id,
            "issued_date": certificate.issued_at.strftime("%Y-%m-%d %H:%M UTC"),
            "disclaimer": _DISCLAIMER,
        })

        pages.append({
            "type": "strategy_summary",
            "user_idea": spec.user_idea,
            "hypothesis": spec.market_hypothesis,
            "entry_conditions": spec.entry_conditions,
            "exit_conditions": spec.exit_conditions,
            "asset_class": spec.asset_class,
            "symbols": ", ".join(spec.symbols),
            "timeframe": spec.timeframe,
            "data_source": spec.data_source,
            "backtest_start": spec.backtest_start,
            "backtest_end": spec.backtest_end,
        })

        degradation = snapshot.degradation_report
        pages.append({
            "type": "performance_evidence",
            "paper_return": snapshot.annualized_return,
            "paper_max_drawdown": snapshot.max_drawdown,
            "paper_sharpe": snapshot.sharpe_ratio,
            "paper_days_deployed": snapshot.days_deployed,
            "paper_total_trades": snapshot.total_trades,
            "paper_win_rate": snapshot.win_rate,
            "backtest_return": backtest.get("mean_sharpe", 0.0),
            "backtest_sharpe": backtest.get("mean_sharpe", 0.0),
            "backtest_max_drawdown": backtest.get("max_drawdown", 0.0),
            "degradation_category": degradation.category if degradation else "N/A",
            "degradation_score": degradation.overall_degradation_score if degradation else 0.0,
        })

        pages.append({
            "type": "methodology_evidence",
            "cpcv_paths": cpcv.get("n_splits", "N/A"),
            "deflated_sharpe": cpcv.get("dsr", "N/A"),
            "overfitting_probability": cpcv.get("overfitting_probability", "N/A"),
            "leakage_verdict": pipeline_result.leakage_verdict or "N/A",
            "review_board_status": pipeline_result.review_board_status or "N/A",
        })

        gate_rows = [
            {
                "name": gr.gate_name,
                "threshold": gr.threshold_value,
                "actual": gr.actual_value,
                "gap": gr.gap,
                "status": gr.status,
            }
            for gr in certificate.gate_results.values()
        ]
        pages.append({
            "type": "graduation_gates",
            "gates": gate_rows,
        })

        pages.append({
            "type": "limitations",
            "limitations": certificate.limitations,
            "disclaimer": _DISCLAIMER,
            "export_timestamp": export_package.exported_at.isoformat(),
            "checksum": export_package.checksum,
        })

        return pages

    def _write_pdf(
        self,
        report_path: str,
        content: list[dict[str, Any]],
        spec: StrategySpec,
        certificate: GraduationCertificate,
        export_package: ExportPackage,
    ) -> None:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                PageBreak, HRFlowable,
            )
        except ImportError:
            self._write_plaintext_fallback(report_path, content)
            return

        doc = SimpleDocTemplate(
            report_path,
            pagesize=letter,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "CoverTitle", parent=styles["Title"],
            fontSize=24, leading=28, spaceAfter=12,
        )
        subtitle_style = ParagraphStyle(
            "CoverSubtitle", parent=styles["Normal"],
            fontSize=14, leading=18, spaceAfter=6,
        )
        heading_style = ParagraphStyle(
            "SectionHeading", parent=styles["Heading1"],
            fontSize=16, leading=20, spaceBefore=16, spaceAfter=8,
        )
        normal_style = ParagraphStyle(
            "ReportNormal", parent=styles["Normal"],
            fontSize=10, leading=14, spaceAfter=4,
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer", parent=styles["Normal"],
            fontSize=8, leading=10, textColor=colors.grey,
            spaceBefore=8, spaceAfter=8,
        )
        small_style = ParagraphStyle(
            "SmallText", parent=styles["Normal"],
            fontSize=9, leading=12, spaceAfter=3,
        )
        code_style = ParagraphStyle(
            "CodeBlock", parent=styles["Code"],
            fontSize=8, leading=10, spaceAfter=4,
            leftIndent=12,
        )

        elements: list[Any] = []

        for page in content:
            ptype = page.get("type", "")

            if ptype == "cover":
                elements.append(Paragraph(page["title"], title_style))
                elements.append(Paragraph(page["subtitle"], subtitle_style))
                elements.append(Spacer(1, 12))
                elements.append(Paragraph(f"Certificate ID: {page['certificate_id']}", small_style))
                elements.append(Paragraph(f"Issued: {page['issued_date']}", small_style))
                elements.append(Spacer(1, 24))
                elements.append(HRFlowable(width="100%", thickness=1))
                elements.append(Spacer(1, 12))
                elements.append(Paragraph(page["disclaimer"], disclaimer_style))

            elif ptype == "strategy_summary":
                elements.append(Paragraph("Strategy Summary", heading_style))
                elements.append(Paragraph(f"<b>Original Idea:</b> {page['user_idea']}", normal_style))
                elements.append(Paragraph(f"<b>Market Hypothesis:</b> {page['hypothesis']}", normal_style))
                elements.append(Paragraph(f"<b>Entry Conditions:</b> {'; '.join(page['entry_conditions'])}", normal_style))
                elements.append(Paragraph(f"<b>Exit Conditions:</b> {'; '.join(page['exit_conditions'])}", normal_style))
                elements.append(Paragraph(f"<b>Asset Class:</b> {page['asset_class']}", normal_style))
                elements.append(Paragraph(f"<b>Symbols:</b> {page['symbols']}", normal_style))
                elements.append(Paragraph(f"<b>Timeframe:</b> {page['timeframe']}", normal_style))
                elements.append(Paragraph(f"<b>Data Source:</b> {page['data_source']}", normal_style))
                elements.append(Paragraph(f"<b>Backtest Period:</b> {page['backtest_start']} to {page['backtest_end']}", small_style))

            elif ptype == "performance_evidence":
                elements.append(Paragraph("Performance Evidence", heading_style))
                elements.append(Spacer(1, 6))
                elements.append(Paragraph("<b>Paper Trading Performance</b>", normal_style))
                paper_data = [
                    ["Metric", "Value"],
                    ["Annualized Return", f"{page['paper_return']:.2%}"],
                    ["Max Drawdown", f"{page['paper_max_drawdown']:.2%}"],
                    ["Sharpe Ratio", f"{page['paper_sharpe']:.2f}"],
                    ["Days Deployed", str(page['paper_days_deployed'])],
                    ["Total Trades", str(page['paper_total_trades'])],
                    ["Win Rate", f"{page['paper_win_rate']:.2%}"],
                ]
                paper_table = Table(paper_data, colWidths=[2.5 * inch, 3 * inch])
                paper_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.2, 0.4, 0.6)),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(paper_table)
                elements.append(Spacer(1, 12))

                elements.append(Paragraph("<b>Backtest Performance</b>", normal_style))
                bt_data = [
                    ["Metric", "Value"],
                    ["Mean Sharpe Ratio", f"{page['backtest_sharpe']:.2f}"],
                ]
                bt_table = Table(bt_data, colWidths=[2.5 * inch, 3 * inch])
                bt_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.2, 0.4, 0.6)),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(bt_table)
                elements.append(Spacer(1, 12))

                elements.append(Paragraph("<b>Degradation Analysis</b>", normal_style))
                elements.append(Paragraph(f"Category: {page['degradation_category']}", small_style))
                elements.append(Paragraph(f"Degradation Score: {page['degradation_score']:.2f}", small_style))

            elif ptype == "methodology_evidence":
                elements.append(Paragraph("Methodology & Evidence", heading_style))
                meth_data = [
                    ["Metric", "Value"],
                    ["CPCV Paths Tested", str(page["cpcv_paths"])],
                    ["Deflated Sharpe Ratio", str(page["deflated_sharpe"])],
                    ["Overfitting Probability", str(page["overfitting_probability"])],
                    ["Leakage Verdict", str(page["leakage_verdict"])],
                    ["Review Board Status", str(page["review_board_status"])],
                ]
                meth_table = Table(meth_data, colWidths=[2.5 * inch, 3 * inch])
                meth_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.2, 0.4, 0.6)),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(meth_table)

            elif ptype == "graduation_gates":
                elements.append(Paragraph("Graduation Gate Evidence", heading_style))
                gate_header = ["Gate", "Threshold", "Actual Value", "Gap", "Status"]
                gate_rows_data = [gate_header]
                for g in page["gates"]:
                    gate_rows_data.append([
                        g["name"],
                        f"{g['threshold']:.4f}",
                        f"{g['actual']:.4f}",
                        f"{g['gap']:.4f}",
                        g["status"],
                    ])
                gate_table = Table(gate_rows_data, colWidths=[1.5 * inch, 1.2 * inch, 1.2 * inch, 1 * inch, 1 * inch])
                gate_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.2, 0.4, 0.6)),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ALIGN", (1, 1), (-1, -1), "CENTER"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(gate_table)

            elif ptype == "limitations":
                elements.append(Paragraph("Limitations & Disclaimers", heading_style))
                for i, lim in enumerate(page["limitations"], 1):
                    elements.append(Paragraph(f"{i}. {lim}", small_style))
                elements.append(Spacer(1, 12))
                elements.append(HRFlowable(width="100%", thickness=1))
                elements.append(Spacer(1, 6))
                elements.append(Paragraph(page["disclaimer"], disclaimer_style))
                elements.append(Paragraph(f"Export Timestamp: {page['export_timestamp']}", code_style))
                elements.append(Paragraph(f"Strategy Checksum (SHA256): {page['checksum']}", code_style))

            elements.append(PageBreak())

        doc.build(elements)

    def _write_plaintext_fallback(
        self, report_path: str, content: list[dict[str, Any]]
    ) -> None:
        txt_path = report_path.replace(".pdf", ".txt")
        lines: list[str] = []

        for page in content:
            ptype = page.get("type", "")
            lines.append("=" * 72)

            if ptype == "cover":
                lines.append(page["title"])
                lines.append(page["subtitle"])
                lines.append(f"Certificate ID: {page['certificate_id']}")
                lines.append(f"Issued: {page['issued_date']}")
                lines.append("")
                lines.append(page["disclaimer"])

            elif ptype == "strategy_summary":
                lines.append("STRATEGY SUMMARY")
                lines.append(f"  Original Idea: {page['user_idea']}")
                lines.append(f"  Hypothesis: {page['hypothesis']}")
                lines.append(f"  Entry: {'; '.join(page['entry_conditions'])}")
                lines.append(f"  Exit: {'; '.join(page['exit_conditions'])}")
                lines.append(f"  Asset Class: {page['asset_class']}")
                lines.append(f"  Symbols: {page['symbols']}")
                lines.append(f"  Timeframe: {page['timeframe']}")

            elif ptype == "performance_evidence":
                lines.append("PERFORMANCE EVIDENCE")
                lines.append(f"  Paper: Return={page['paper_return']:.2%}, DD={page['paper_max_drawdown']:.2%}, Sharpe={page['paper_sharpe']:.2f}")
                lines.append(f"  Backtest: Sharpe={page['backtest_sharpe']:.2f}")
                lines.append(f"  Degradation: {page['degradation_category']} (score={page['degradation_score']:.2f})")

            elif ptype == "methodology_evidence":
                lines.append("METHODOLOGY EVIDENCE")
                lines.append(f"  CPCV Paths: {page['cpcv_paths']}")
                lines.append(f"  DSR: {page['deflated_sharpe']}")
                lines.append(f"  Overfitting Probability: {page['overfitting_probability']}")
                lines.append(f"  Leakage: {page['leakage_verdict']}")
                lines.append(f"  Review Board: {page['review_board_status']}")

            elif ptype == "graduation_gates":
                lines.append("GRADUATION GATES")
                for g in page["gates"]:
                    lines.append(f"  [{g['status']}] {g['name']}: {g['actual']:.4f} vs {g['threshold']:.4f} (gap={g['gap']:.4f})")

            elif ptype == "limitations":
                lines.append("LIMITATIONS AND DISCLAIMERS")
                for i, lim in enumerate(page["limitations"], 1):
                    lines.append(f"  {i}. {lim}")
                lines.append("")
                lines.append(page["disclaimer"])
                lines.append(f"  Export: {page['export_timestamp']}")
                lines.append(f"  Checksum: {page['checksum']}")

            lines.append("")

        with open(txt_path, "w") as f:
            f.write("\n".join(lines))
