"""Strategy templates and base class for AURORA-compatible strategies."""

from abc import ABC, abstractmethod

import pandas as pd


class BaseStrategy(ABC):
    STRATEGY_TYPE: str = ""
    STRATEGY_HYPOTHESIS: str = ""

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        ...

    @abstractmethod
    def get_parameters(self) -> dict:
        ...

    @abstractmethod
    def get_parameter_bounds(self) -> dict:
        ...


TREND_FOLLOWING_TEMPLATE = '''
"""Strategy generated by ASTRA — trend following."""

import pandas as pd
from astra.builder.templates import BaseStrategy


class TrendFollowingStrategy(BaseStrategy):
    STRATEGY_TYPE = "trend_following"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 fast_window: int = {fast_window},
                 slow_window: int = {slow_window},
                 signal_threshold: float = {signal_threshold}):
        self.fast_window = fast_window
        self.slow_window = slow_window
        self.signal_threshold = signal_threshold

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        fast_ma = data["close"].rolling(window=self.fast_window).mean()
        slow_ma = data["close"].rolling(window=self.slow_window).mean()
        signal = (fast_ma > slow_ma * (1 + self.signal_threshold)).astype(int)
        return signal

    def get_parameters(self) -> dict:
        return {{
            "fast_window": self.fast_window,
            "slow_window": self.slow_window,
            "signal_threshold": self.signal_threshold,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "fast_window": (5, 50),
            "slow_window": (20, 200),
            "signal_threshold": (0.01, 0.10),
        }}
'''

MEAN_REVERSION_TEMPLATE = '''
"""Strategy generated by ASTRA — mean reversion."""

import pandas as pd
from astra.builder.templates import BaseStrategy


class MeanReversionStrategy(BaseStrategy):
    STRATEGY_TYPE = "mean_reversion"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 rsi_window: int = {rsi_window},
                 oversold_threshold: float = {oversold_threshold},
                 overbought_threshold: float = {overbought_threshold}):
        self.rsi_window = rsi_window
        self.oversold_threshold = oversold_threshold
        self.overbought_threshold = overbought_threshold

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        delta = data["close"].diff()
        gain = delta.where(delta > 0, 0.0).rolling(window=self.rsi_window).mean()
        loss = (-delta.where(delta < 0, 0.0)).rolling(window=self.rsi_window).mean()
        rs = gain / loss.replace(0, float("nan"))
        rsi = 100.0 - (100.0 / (1.0 + rs))
        signal = (rsi < self.oversold_threshold).astype(int)
        return signal

    def get_parameters(self) -> dict:
        return {{
            "rsi_window": self.rsi_window,
            "oversold_threshold": self.oversold_threshold,
            "overbought_threshold": self.overbought_threshold,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "rsi_window": (5, 30),
            "oversold_threshold": (20.0, 40.0),
            "overbought_threshold": (60.0, 80.0),
        }}
'''

MOMENTUM_TEMPLATE = '''
"""Strategy generated by ASTRA — momentum."""

import pandas as pd
from astra.builder.templates import BaseStrategy


class MomentumStrategy(BaseStrategy):
    STRATEGY_TYPE = "momentum"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 lookback_window: int = {lookback_window},
                 momentum_threshold: float = {momentum_threshold},
                 holding_period: int = {holding_period}):
        self.lookback_window = lookback_window
        self.momentum_threshold = momentum_threshold
        self.holding_period = holding_period

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        returns = data["close"].pct_change(periods=self.lookback_window)
        raw_signal = (returns > self.momentum_threshold).astype(int)
        signal = raw_signal.rolling(window=self.holding_period).max().fillna(0).astype(int)
        return signal

    def get_parameters(self) -> dict:
        return {{
            "lookback_window": self.lookback_window,
            "momentum_threshold": self.momentum_threshold,
            "holding_period": self.holding_period,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "lookback_window": (5, 252),
            "momentum_threshold": (0.01, 0.20),
            "holding_period": (1, 60),
        }}
'''

PAIRS_TEMPLATE = '''
"""Strategy generated by ASTRA — pairs trading."""

import pandas as pd
from astra.builder.templates import BaseStrategy


class PairsStrategy(BaseStrategy):
    STRATEGY_TYPE = "pairs"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 z_entry: float = {z_entry},
                 z_exit: float = {z_exit},
                 lookback_window: int = {lookback_window}):
        self.z_entry = z_entry
        self.z_exit = z_exit
        self.lookback_window = lookback_window

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        ratio = data["close_leg1"] / data["close_leg2"]
        mean = ratio.rolling(window=self.lookback_window).mean()
        std = ratio.rolling(window=self.lookback_window).std()
        z_score = (ratio - mean) / std.replace(0, float("nan"))
        signal = (z_score < -self.z_entry).astype(int)
        return signal

    def get_parameters(self) -> dict:
        return {{
            "z_entry": self.z_entry,
            "z_exit": self.z_exit,
            "lookback_window": self.lookback_window,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "z_entry": (1.0, 3.0),
            "z_exit": (0.0, 1.0),
            "lookback_window": (10, 100),
        }}
'''

BREAKOUT_TEMPLATE = '''
"""Strategy generated by ASTRA — breakout."""

import pandas as pd
from astra.builder.templates import BaseStrategy


class BreakoutStrategy(BaseStrategy):
    STRATEGY_TYPE = "breakout"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 lookback_window: int = {lookback_window},
                 breakout_multiplier: float = {breakout_multiplier},
                 volume_threshold: float = {volume_threshold}):
        self.lookback_window = lookback_window
        self.breakout_multiplier = breakout_multiplier
        self.volume_threshold = volume_threshold

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        high_max = data["high"].rolling(window=self.lookback_window).max()
        vol_ma = data["volume"].rolling(window=self.lookback_window).mean()
        price_breakout = data["close"] > high_max.shift(1) * self.breakout_multiplier
        volume_confirm = data["volume"] > vol_ma * self.volume_threshold
        signal = (price_breakout & volume_confirm).astype(int)
        return signal

    def get_parameters(self) -> dict:
        return {{
            "lookback_window": self.lookback_window,
            "breakout_multiplier": self.breakout_multiplier,
            "volume_threshold": self.volume_threshold,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "lookback_window": (10, 100),
            "breakout_multiplier": (1.0, 3.0),
            "volume_threshold": (1.0, 3.0),
        }}
'''

DCA_TEMPLATE = '''
"""Strategy generated by ASTRA — dollar-cost averaging."""

import pandas as pd
from astra.builder.templates import BaseStrategy


class DCAStrategy(BaseStrategy):
    STRATEGY_TYPE = "dca"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 investment_interval_days: int = {investment_interval_days},
                 max_positions: int = {max_positions},
                 investment_fraction: float = {investment_fraction}):
        self.investment_interval_days = investment_interval_days
        self.max_positions = max_positions
        self.investment_fraction = investment_fraction

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        signal = pd.Series(0, index=data.index)
        if len(data) == 0:
            return signal
        buy_indices = range(self.investment_interval_days - 1, len(data), self.investment_interval_days)
        signal.iloc[buy_indices] = 1
        return signal

    def get_parameters(self) -> dict:
        return {{
            "investment_interval_days": self.investment_interval_days,
            "max_positions": self.max_positions,
            "investment_fraction": self.investment_fraction,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "investment_interval_days": (1, 30),
            "max_positions": (4, 52),
            "investment_fraction": (0.01, 0.25),
        }}
'''

STAT_ARB_TEMPLATE = '''
"""Strategy generated by ASTRA — statistical arbitrage."""
import pandas as pd
import numpy as np
from astra.builder.templates import BaseStrategy


class StatArbStrategy(BaseStrategy):
    STRATEGY_TYPE = "stat_arb"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 z_entry: float = {z_entry},
                 z_exit: float = {z_exit},
                 hedge_ratio_window: int = {hedge_ratio_window},
                 half_life_window: int = {half_life_window}):
        self.z_entry = z_entry
        self.z_exit = z_exit
        self.hedge_ratio_window = hedge_ratio_window
        self.half_life_window = half_life_window

    def _spread(self, data: pd.DataFrame) -> pd.Series:
        leg1 = data["close_leg1"]
        leg2 = data["close_leg2"]
        ratio = leg1 / leg2
        hedge_ratio = ratio.rolling(self.hedge_ratio_window).mean()
        return leg1 - hedge_ratio * leg2

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        spread = self._spread(data)
        mean = spread.rolling(self.half_life_window).mean()
        std = spread.rolling(self.half_life_window).std().replace(0, np.nan)
        z = (spread - mean) / std
        signal = pd.Series(0, index=data.index)
        signal[z < -self.z_entry] = 1
        signal[z > self.z_entry] = -1
        return signal

    def get_parameters(self) -> dict:
        return {{
            "z_entry": self.z_entry,
            "z_exit": self.z_exit,
            "hedge_ratio_window": self.hedge_ratio_window,
            "half_life_window": self.half_life_window,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "z_entry": (1.0, 3.0),
            "z_exit": (0.0, 1.0),
            "hedge_ratio_window": (10, 100),
            "half_life_window": (5, 60),
        }}
'''

VWAP_MOMENTUM_TEMPLATE = '''
"""Strategy generated by ASTRA — volume-weighted momentum."""
import pandas as pd
import numpy as np
from astra.builder.templates import BaseStrategy


class VWAPMomentumStrategy(BaseStrategy):
    STRATEGY_TYPE = "vwap_momentum"
    STRATEGY_HYPOTHESIS = "{hypothesis}"

    def __init__(self,
                 vwap_window: int = {vwap_window},
                 momentum_window: int = {momentum_window},
                 deviation_threshold: float = {deviation_threshold}):
        self.vwap_window = vwap_window
        self.momentum_window = momentum_window
        self.deviation_threshold = deviation_threshold

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        tp = (data["high"] + data["low"] + data["close"]) / 3
        vwap = (tp * data["volume"]).rolling(self.vwap_window).sum() / data["volume"].rolling(self.vwap_window).sum()
        momentum = data["close"].pct_change(self.momentum_window)
        deviation = (data["close"] - vwap) / vwap
        signal = ((deviation.abs() < self.deviation_threshold) & (momentum > 0)).astype(int)
        return signal

    def get_parameters(self) -> dict:
        return {{
            "vwap_window": self.vwap_window,
            "momentum_window": self.momentum_window,
            "deviation_threshold": self.deviation_threshold,
        }}

    def get_parameter_bounds(self) -> dict:
        return {{
            "vwap_window": (5, 50),
            "momentum_window": (5, 60),
            "deviation_threshold": (0.01, 0.10),
        }}
'''

TEMPLATES_BY_TYPE = {
    "trend_following": TREND_FOLLOWING_TEMPLATE,
    "mean_reversion": MEAN_REVERSION_TEMPLATE,
    "momentum": MOMENTUM_TEMPLATE,
    "pairs": PAIRS_TEMPLATE,
    "breakout": BREAKOUT_TEMPLATE,
    "dca": DCA_TEMPLATE,
    "stat_arb": STAT_ARB_TEMPLATE,
    "vwap_momentum": VWAP_MOMENTUM_TEMPLATE,
}

DEFAULT_PARAMETERS_BY_TYPE = {
    "trend_following": {
        "fast_window": 20,
        "slow_window": 50,
        "signal_threshold": 0.02,
    },
    "mean_reversion": {
        "rsi_window": 14,
        "oversold_threshold": 30.0,
        "overbought_threshold": 70.0,
    },
    "momentum": {
        "lookback_window": 126,
        "momentum_threshold": 0.05,
        "holding_period": 21,
    },
    "pairs": {
        "z_entry": 2.0,
        "z_exit": 0.5,
        "lookback_window": 20,
    },
    "breakout": {
        "lookback_window": 20,
        "breakout_multiplier": 1.02,
        "volume_threshold": 1.5,
    },
    "dca": {
        "investment_interval_days": 7,
        "max_positions": 52,
        "investment_fraction": 0.05,
    },
    "stat_arb": {
        "z_entry": 2.0,
        "z_exit": 0.5,
        "hedge_ratio_window": 30,
        "half_life_window": 20,
    },
    "vwap_momentum": {
        "vwap_window": 20,
        "momentum_window": 21,
        "deviation_threshold": 0.03,
    },
}

CLASS_NAME_BY_TYPE = {
    "trend_following": "TrendFollowingStrategy",
    "mean_reversion": "MeanReversionStrategy",
    "momentum": "MomentumStrategy",
    "pairs": "PairsStrategy",
    "breakout": "BreakoutStrategy",
    "dca": "DCAStrategy",
    "stat_arb": "StatArbStrategy",
    "vwap_momentum": "VWAPMomentumStrategy",
}
